sonar.projectKey=mangalit_Manajemen-klinik-kelompok-8
sonar.organization=mangalit
sonar.sources=app,resources/views,routes
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=junit.xml
sonar.exclusions=vendor/**,public/**,database/**,node_modules/**,storage/**
sonar.sourceEncoding=UTF-8
